In [1]:
import numpy as np

In [2]:
[1, 6, 5, 2] * [7, 3, 1, 1]

TypeError: can't multiply sequence by non-int of type 'list'

In [4]:
first = np.array([1, 6, 5, 2])
second = np.array([7, 3, 1, 1])

In [5]:
first * second

array([ 7, 18,  5,  2])

In [6]:
first + second

array([8, 9, 6, 3])

In [14]:
first = np.matrix([[1, 7, 5], [7, 8, 9], [5, 5, 5], [3, 4, 1]])
second = np.matrix([[7, 4], [2, 1], [9, 10]])

In [17]:
first * second

matrix([[ 66,  61],
        [146, 126],
        [ 90,  75],
        [ 38,  26]])